### ISSUE TITLE
SwapIsolator의 제안 (SchedIsolator의 확장)

### ISSUE THREAD

**Issue by YoonsungNam** [dcslab-snu/iso-sched#18]
Overview
-
`SchedIsolator`는 현재 Background 워크로드에 할당된 **코어의 수**를 조절하여 컨탠션을 줄이는 Isolator이다.
현재는 1 socket에서 코어의 수를 줄이는 방식으로 스케줄하고 있지만 2 socket 이상에서의 컨탠션을 줄이는 방식으로 다음을 제안함.

Design
-
**SchedIsolator (Current)**

- `SchedIsolator`는 BG 워크로드의 코어수를 조절함

**SchedIsolator (Proposal)**

- `SchedIsolator`는 2 socket이상의 코어를 활용할 수 있는 상황에서 FG 워크로드의 성능간섭 최소화를 위한 Isolation으로 현재소켓의 Co-located BG 워크로드들을 다른소켓의 BG 워크로드와 교환함

  - 이러한 조치는 `SchedIsolator`의 기능을 추가 확장하는 것으로 하나의 소켓에서 처리불가능한 심한 경합을 줄이는 방식으로 다른 Isolation 테크닉들(`Partitioning`과 `Throttling`)의 단점을 메우는 방안임

Implementation
-
이러한 구현을 위해서는 현재의 `SchedIsolator`보다 상위의 Class를 만들고, 제안하는 기능(Proposal)을 구현해야할 것으로 생각됨.
- `SchedIsolator`의 상위 클래스를 만들고, 현재의 `SchedIsolator`가 이를 상속받도록 구현 (Naming변경도 필요할듯함)
- `SwapIsolator` 클래스(가제)를 만들고, 현재의 `SchedIsolator`가 상속받는 상위클래스를 상속받아 제안하는 기능을 구현할 것. 이를 위해서는 컨트롤러가 소켓단위로 워크로드들을 관리하여야 하므로 **Hard coding된 부분들이 변경되어야할 수 있음**
  - `SwapIsolator`를 위해서는 애초에 맨처음 **`numactl`을 사용하는 부분을 모두 `cgroup`으로 구현하는게 필요함.** 왜냐하면, numactl은 워크로드의 Re-location에 사용되는데 부적합하기 때문임
  - `cgroup`의 `memory` subsystem을 사용한다면, 특정 워크로드가 할당될 memory node affinity를 조절할 수 있을것으로 기대되고, 기존의 `SchedIsolator`의 Interface인 `cpuset` subsystem과도 통합이 용이할듯함.

**Comment by YoonsungNam** [comment]
**추가고려사항**

`cpuset.mems`를 이용해서 memory node affinity를 주는 식으로 수정중이며, `SwapIsolator`를 통해서 소켓을 이동했을시 remote memory access가 되지 않도록 하려면 `cpuset.memory_migrate`값을 1로 설정해주어야 함.

> cpuset.memory_migrate
> cpuset.mems의 값이 변경되면 메모리의 페이지가 새로운 노드로 이동해야 하는지를 지정하는 플래그(0또는 1)를 포함합니다. 디폴트로 메모리 이동은 금지(0)되어 있으며, 페이지는 최초 할당된 메모리 노드에 남아있게 됩니다. 심지어 cpuset.mems에 새롭게 지정된 노드가 최초 할당된 노드와 달라지는 경우에도 그렇습니다. 만약 활성화(1)되면 시스템은 페이지를 cpuset.mems에 지정된 새로운 매개변수에 맞춰, 가능하면 상대적인 위치도 유지하면서, 이동시킬 것입니다. 예를 들어 cpuset.mems에 의해 최초 두번째 노드에 있도록 지정된 페이지들은 cpuset.mems에 의해 새로 지정된 두번째 노드가 사용 가능하다면 그 노드에 할당될 것입니다.

Reference : [link](https://access.redhat.com/documentation/ko-kr/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpuset)

**Comment by isac322** [comment]
Isolator로 구현할 시 isolator간의 순서 문제로 독립된 swapper로 개발
