### ISSUE TITLE
새로운 isolator 선택되는 경우에, 첫 configuration선택할 때 오류가 있음

### ISSUE THREAD

**Issue by isac322** [dcslab-snu/iso-sched#3]
#### 컨트롤러 알고리즘

1. 워크로드 생성 & 모니터링 시작
2. isolator 선택
3. configuration 선택
4. diff값 생성 (prev_diff)
5. enforce
6. controller interval 만큼 대기
7. diff값 생성 (curr_diff)
8. diff_of_diff = curr_diff - prev_diff 계산
9. (3)부터 다시
  9-1. configuration이 완료되지 않은 경우에만
10. (2)부터 다시

컨트롤러 알고리즘에서 (3)을 통과하는 경우가 각각

1. (1)에서 혹은 (10)에서
    - 두 경우로 나눠서 생각할 수 있는데
        1. isolator가 처음 선택되어 첫 configuration 선택
        2. 한번 선택되었던 isolator가 다시 선택되어, 다음 configuration 선택
2. (9)에서
    - 같은 isolator에서 다음 configuration 선택

이다.

2의 경우 기존의 알고리즘에 의해 자동으로 선택되지만,
1의 두 경우 isolator가 새로 시작할 때 첫 configuration을 어떤것으로 할것이냐를 결정해야한다.

### 제안
1-1의 경우 무조건 `STRENGTHEN`으로 간다거나, 1-2의 경우 그 전 configuration을 기억 후 결정하는 방식으로 우선 고쳐볼 수 있다

**Comment by YoonsungNam** [comment]
isolator가 처음 선택될때, offline 데이터를 바탕으로 시작한다면, isolator 호출하는 횟수(2~10 루프)를 줄일 수 있지않을까함.

**Comment by isac322** [comment]
일단 무조건 `STRENGTHEN`을 선택하도록 하드코딩 했는데, 나중에 어떤것을 선택할지 선택하는 로직도 추가해야할듯

**Comment by isac322** [comment]
일단은 바로 위에말한 하드코딩 된 방식으로 해결.
나중에 이 부분을 다시 고민할 일이 생기면 reopen 필요
