### ISSUE TITLE
SchedIsolator의 변경 제안 (CoreIsolator)

### ISSUE THREAD

**Issue by YoonsungNam** [dcslab-snu/iso-sched#31]
현재 `SchedIsolator`는 원래의 Naming 컨벤션(Resource이름과 Isolator를 결합하는 방식)과 충돌하는 경향이 있음
따라서, 이름을 CoreIsolator로 변경하고자 함.

그리고 현재 하드코딩되어 있는 부분은 2개 워크로드를 가정하여, BG 워크로드의 성능만을 변경하기 위해서 되어있음. **따라서 하드코딩된 부분을 없앰과 동시에 FG, BG 워크로드 동시에 코어할당을 조절해줄 수 있는 Isolator로 기능을 업그레이드하는 방향으로 고칠 필요가 있음.**

**`CoreIsolator` 변경 제안**
- `cur_step`으로 되어있는 부분을 제거하고, `cpuset`개념으로 하여 `strengthen`과 `weaken` 및 관련 코드들을 변경구현
- BG 워크로드의 CoreIsolation만 하는것이 아닌 FG 워크로드의 Core또한 늘려줄 수 있는 방식으로 구현
  - 이러한 방식은 CPU수보다 Thread수가 많은 Bursty한 상황(웹서버의 Request가 증가하여 Thread가 갑자기 많이 필요한 상황)에서 FG 워크로드의 성능을 향상시킬 수 있음

**Comment by YoonsungNam** [comment]
클래스 이름 SchedIsolator->CoreIsolator로 변경

**Comment by YoonsungNam** [comment]
현재 FG workload의 `Next.strengthen`과 `Next.weaken`의 진입조건을 결정해줘야함. 
LLC처럼 **항상** BG와 FG가 양분하는 식으로 구현하든지 DVFS처럼 BG만 조절하는 식으로 구현하든지 해야함

**Comment by YoonsungNam** [comment]
추가/변경된 로직

- 현재 `strengthen()`과 `weaken()`에서 각각 fg의 `NextStep`을 보는 로직
- `_monitoring_result()`에서 `NextStep.STOP`의 조건 변경
- `fg_strengthen_cond` 와 `fg_weaken_cond`의 조건 추가

**Comment by isac322** [comment]
두 기능을 core isolator에 한번에 구현 시, step조정과 core isolator의 적용대상 판별에 문제가 있어 #40 에서 두 기능으로 나눠서 구현
