### ISSUE TITLE
Latency-sensitive process의 solo-run data 측정

### ISSUE THREAD

**Issue by YoonsungNam** [dcslab-snu/iso-sched#35]
현재 구현 중인 scheduler는 항상 isolation을 위해서 solo-run 데이터를 필요로 한다.
batch process의 경우 solorun 데이터를 측정해두었지만 latency-senstivie process의 경우 그러한 데이터가 없으므로, isolator에서 metric_diff를 계산할 시 에러가 발생할 수 밖에 없음.

현재 latency-sentivie process에 대해서 어떻게 solo-run data를 적용하는지에 대한 메커니즘이 필요함

**Comment by isac322** [comment]
나중에 정말 dynamic하게 하려면 이 문제를 해결해야하긴 하겠지만, 일단 지금은 제가 만든 dab의 load generation을 통해 만든 load를 solorun에서 돌린 값으로 넣고 돌리는 방식으로 했어요.

**Comment by YoonsungNam** [comment]
Solo-run data의 기준을 정할 Load는 다음과 같이 정하면 좋을 듯함. 

- LS워크로드를 소켓의 절반인 8core를 기준으로 하여 셋업을 하고 
- LS워크로드가 Solo-run시, 99%ile Target Latency가 (e.g., sub-100ms와 같은) SLO를 유지할 수 있는 Load를 구함
- 구한 Load를 이용해서 LS 워크로드를 수행할 때, LS 워크로드의 Metric값을 구하여 이를 LS 워크로드의 Solo-run data로 정함
- 스케줄러는 해당 Solo-run data와의 diff값을 보면서 Solo-run의 워크로드를 지켜주도록 함

**Comment by isac322** [comment]
#40 의 online profiling으로 해결
